### ISSUE TITLE
Split the op-stack into a standalone repository

### ISSUE THREAD

**Issue by dndll** [near/rollup-data-availability#29]
make sure to retain the same structure so we can get upstream updates for free.

Blocked by https://github.com/near/rollup-data-availability/issues/31
```[tasklist]
### Tasks
- [ ] Same structure as optimism
- [ ] CI ticket
- [ ] Pulling da-rpc-go
- [ ] Remove go workspace hack
- [ ] Remove builder magic for docker images
- [ ] Use the newly published da-rpc-go pkg
```
