### ISSUE TITLE
Split polygon cdk into a standalone repository

### ISSUE THREAD

**Issue by dndll** [near/rollup-data-availability#30]
blocked by https://github.com/near/rollup-data-availability/issues/31
```[tasklist]
### Tasks
- [ ] Pushing docker images
- [ ] Additional ticket for CI
- [ ] Remove builder magic for docker images
- [ ] Remove go workspace hack
- [ ] Use the newly published da-rpc-go pkg
```
