### ISSUE TITLE
Better repository structure

### ISSUE THREAD

**Issue by carrion256** [near/rollup-data-availability#32]
Currently, the naming of everything and place it lives is unorthodox. 

For example:
- ./op-stack/da-rpc implies this is for optimism, but this is also used by polygon
- ./crates/op-rpc-* is the same as above

```[tasklist]
### Tasks
- [x] Rename ./crates/op-rpc to `./crates/da-rpc` and *-sys, make sure the manifest is `near-da-rpc` and `*-sys`
- [x] Ensure docker images build and the naming is appropriate
- [x] Move ./op-stack/da-rpc to ./gopkg/da-rpc-go and ensure the package is named `github.com/near/rollup-data-availability/da-rpc-go`, ensure Docker images and FFI works.
- [x] go.work for cdk & op-stack should be updated
- [x] scripts for *-sys install should point to new directory
- [x] Ensure the header file for da-rpc-sys is nice and works with the build script
```
